<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LocalsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('locals')->insert([[
            'nome' 		        => 'Zazie',
            'indirizzo' 	    => 'Via San Romano, 62',
            'num_tavoli'	    => '4',
            'id_ristoratore' 	=> '14',
            'disp_massima' 	    => '10',
            'menu' 	            => '5',
            'pianta' 	        => '',
            'updated_at' 	    => date('Y-m-d h:i:s'),
            'created_at' 	    => date('Y-m-d h:i:s'),
            'tipo' 	            => 'Bar',
            'sponsorizzato'     => '1',
            'link_immagine'     => 'd2egcvq7li5bpq.cloudfront.net/it/images/restaurants/238452.gif',
            'info' 	            => 'Bevande e Cibo vegetariano o vegano',
        ], [
            'nome' 		        => 'Archibugio',
            'indirizzo' 	    => 'Via Saragat, 1',
            'num_tavoli'	    => '12',
            'id_ristoratore' 	=> '14',
            'disp_massima' 	    => '48',
            'menu' 	            => '6',
            'pianta' 	        => '',
            'updated_at' 	    => date('Y-m-d h:i:s'),
            'created_at' 	    => date('Y-m-d h:i:s'),
            'tipo' 	            => 'Bar',
            'sponsorizzato'     => '0',
            'link_immagine'     => 'd2egcvq7li5bpq.cloudfront.net/it/images/restaurants/238452.gif',
            'info' 	            => 'Bar Universitario situato nel Polo Scientifico e Tecnologico',
        ], [
            'nome' 		        => 'Tiki Bar',
            'indirizzo' 	    => 'Via Carlo Mayr, 7',
            'num_tavoli'	    => '6',
            'id_ristoratore' 	=> '14',
            'disp_massima' 	    => '30',
            'menu' 	            => '7',
            'pianta' 	        => '',
            'updated_at' 	    => date('Y-m-d h:i:s'),
            'created_at' 	    => date('Y-m-d h:i:s'),
            'tipo' 	            => 'Bar',
            'sponsorizzato'     => '0',
            'link_immagine'     => 'https://instagram.fblq3-1.fna.fbcdn.net/v/t51.2885-19/s150x150/67839209_2356400247763202_4714677255421296640_n.jpg?_nc_ht=instagram.fblq3-1.fna.fbcdn.net&_nc_ohc=ZQpnu_2904MAX-mMreJ&tp=1&oh=7f2900fff61da4c7b38e9a625a766543&oe=6038A048',
            'info' 	            => 'Atmosfera Hawaiiana in pieno centro a Ferrara',
        ], [
            'nome' 		        => 'Chocolat',
            'indirizzo' 	    => 'Via Cortevecchia, 55',
            'num_tavoli'	    => '5',
            'id_ristoratore' 	=> '14',
            'disp_massima' 	    => '20',
            'menu' 	            => '8',
            'pianta' 	        => '',
            'updated_at' 	    => date('Y-m-d h:i:s'),
            'created_at' 	    => date('Y-m-d h:i:s'),
            'tipo' 	            => 'Bar',
            'sponsorizzato'     => '1',
            'link_immagine'     => 'https://chocolat-ferrara.it/wp-content/uploads/2019/04/Choco_346x92_retina.png',
            'info' 	            => 'Bar Pasticceria',
        ], [
            'nome' 		        => 'Maracaibo',
            'indirizzo' 	    => 'Via Contrari, 13',
            'num_tavoli'	    => '10',
            'id_ristoratore' 	=> '15',
            'disp_massima' 	    => '50',
            'menu' 	            => '9',
            'pianta' 	        => '',
            'updated_at' 	    => date('Y-m-d h:i:s'),
            'created_at' 	    => date('Y-m-d h:i:s'),
            'tipo' 	            => 'Pub',
            'sponsorizzato'     => '0',
            'link_immagine'     => 'https://instagram.fblq3-1.fna.fbcdn.net/v/t51.2885-19/s150x150/122146094_198251108377370_1308727547434782441_n.jpg?_nc_ht=instagram.fblq3-1.fna.fbcdn.net&_nc_ohc=1a44UYMfc4UAX-CVlDs&tp=1&oh=41157ab0876a575471f88faa79db2058&oe=603AC7F7',
            'info' 	            => 'Ampio spazio in centro a Ferrara',
        ], [
            'nome' 		        => 'Il Molo',
            'indirizzo' 	    => 'Via Contrari, 36',
            'num_tavoli'	    => '4',
            'id_ristoratore' 	=> '15',
            'disp_massima' 	    => '20',
            'menu' 	            => '10',
            'pianta' 	        => '',
            'updated_at' 	    => date('Y-m-d h:i:s'),
            'created_at' 	    => date('Y-m-d h:i:s'),
            'tipo' 	            => 'Pub',
            'sponsorizzato'     => '0',
            'link_immagine'     => 'https://instagram.fblq3-1.fna.fbcdn.net/v/t51.2885-19/s150x150/46153630_2230754403876975_5887304039917420544_n.jpg?_nc_ht=instagram.fblq3-1.fna.fbcdn.net&_nc_ohc=hiw91ssXcX4AX9IjBBh&tp=1&oh=71a98c179cd4730c1375d79eb39ed771&oe=60394ADC',
            'info' 	            => 'Pub in stile inglese',
        ], [
            'nome' 		        => 'Birra Frara',
            'indirizzo' 	    => 'Via San Romano, 90',
            'num_tavoli'	    => '8',
            'id_ristoratore' 	=> '15',
            'disp_massima' 	    => '60',
            'menu' 	            => '11',
            'pianta' 	        => '',
            'updated_at' 	    => date('Y-m-d h:i:s'),
            'created_at' 	    => date('Y-m-d h:i:s'),
            'tipo' 	            => 'Pub',
            'sponsorizzato'     => '1',
            'link_immagine'     => 'd2egcvq7li5bpq.cloudfront.net/it/images/restaurants/226760.gif',
            'info' 	            => 'Birre artigianali prodotte nella zona',              
        ], [
            'nome' 		        => 'Korova Milk Bar',
            'indirizzo' 	    => 'Via Croce Bianca, 51',
            'num_tavoli'	    => '10',
            'id_ristoratore' 	=> '15',
            'disp_massima' 	    => '40',
            'menu' 	            => '12',
            'pianta' 	        => '',
            'updated_at' 	    => date('Y-m-d h:i:s'),
            'created_at' 	    => date('Y-m-d h:i:s'),
            'tipo' 	            => 'Pub',
            'sponsorizzato'     => '0',
            'link_immagine'     => 'https://instagram.fblq3-1.fna.fbcdn.net/v/t51.2885-19/s150x150/94269254_1337105863161299_5548949724679110656_n.jpg?_nc_ht=instagram.fblq3-1.fna.fbcdn.net&_nc_ohc=Yi15HO-9IRwAX_umt5m&tp=1&oh=f24f25dff23ae540eddf0ab2b568447d&oe=6038A1EC',
            'info' 	            => 'Bar ispirato al capolavoro di Kubrick',    
        ], [
            'nome' 		        => 'Collins',
            'indirizzo' 	    => 'Via Padova, 261',
            'num_tavoli'	    => '12',
            'id_ristoratore' 	=> '16',
            'disp_massima' 	    => '70',
            'menu' 	            => '13',
            'pianta' 	        => '',
            'updated_at' 	    => date('Y-m-d h:i:s'),
            'created_at' 	    => date('Y-m-d h:i:s'),
            'tipo' 	            => 'Pub',
            'sponsorizzato'     => '0',
            'link_immagine'     => 'https://instagram.fblq3-1.fna.fbcdn.net/v/t51.2885-19/s150x150/82154833_3021770911190579_4779764705948336128_n.jpg?_nc_ht=instagram.fblq3-1.fna.fbcdn.net&_nc_ohc=EacD4MWlQVMAX-SIGdD&tp=1&oh=4cb980151d1bfc9d00eb61f55a024996&oe=60383FCD',
            'info' 	            => 'Irish Pub',    
        ], [
            'nome' 		        => 'Punto-Veg',
            'indirizzo' 	    => 'Via Carlo Mayr, 72',
            'num_tavoli'	    => '5',
            'id_ristoratore' 	=> '16',
            'disp_massima' 	    => '30',
            'menu' 	            => '14',
            'pianta' 	        => '',
            'updated_at' 	    => date('Y-m-d h:i:s'),
            'created_at' 	    => date('Y-m-d h:i:s'),
            'tipo' 	            => 'Ristorante',
            'sponsorizzato'     => '1',
            'link_immagine'     => 'd2egcvq7li5bpq.cloudfront.net/it/images/restaurants/210165.gif',
            'info' 	            => 'Cucina Vegana',    
        ], [
            'nome' 		        => 'Orsucci',
            'indirizzo' 	    => 'Via Saraceno, 116',
            'num_tavoli'	    => '4',
            'id_ristoratore' 	=> '16',
            'disp_massima' 	    => '20',
            'menu' 	            => '15',
            'pianta' 	        => '',
            'updated_at' 	    => date('Y-m-d h:i:s'),
            'created_at' 	    => date('Y-m-d h:i:s'),
            'tipo' 	            => 'Ristorante',
            'sponsorizzato'     => '0',
            'link_immagine'     => 'd2egcvq7li5bpq.cloudfront.net/it/images/restaurants/226965.gif',
            'info' 	            => 'Pizza e Ceci',
        ], [
            'nome' 		        => 'Li-Xia',
            'indirizzo' 	    => 'Piazza Sacrati, 43',
            'num_tavoli'	    => '15',
            'id_ristoratore' 	=> '16',
            'disp_massima' 	    => '80',
            'menu' 	            => '16',
            'pianta' 	        => '',
            'updated_at' 	    => date('Y-m-d h:i:s'),
            'created_at' 	    => date('Y-m-d h:i:s'),
            'tipo' 	            => 'Ristorante',
            'sponsorizzato'     => '1',
            'link_immagine'     => 'd2egcvq7li5bpq.cloudfront.net/it/images/restaurants/226963.gif',
            'info' 	            => 'Cucina Cinese',
        ], [
            'nome' 		        => 'Burger King',
            'indirizzo' 	    => 'Via Richard Wagner, 10/12',
            'num_tavoli'	    => '15',
            'id_ristoratore' 	=> '16',
            'disp_massima' 	    => '100',
            'menu' 	            => '17',
            'pianta' 	        => '',
            'updated_at' 	    => date('Y-m-d h:i:s'),
            'created_at' 	    => date('Y-m-d h:i:s'),
            'tipo' 	            => 'Ristorante',
            'sponsorizzato'     => '1',
            'link_immagine'     => 'd2egcvq7li5bpq.cloudfront.net/it/images/restaurants/226967.gif',
            'info' 	            => 'Hamburger Americano',
        ], [
            'nome' 		        => 'Schiaccia',
            'indirizzo' 	    => 'Via San Romano, 73',
            'num_tavoli'	    => '8',
            'id_ristoratore' 	=> '17',
            'disp_massima' 	    => '65',
            'menu' 	            => '18',
            'pianta' 	        => '',
            'updated_at' 	    => date('Y-m-d h:i:s'),
            'created_at' 	    => date('Y-m-d h:i:s'),
            'tipo' 	            => 'Ristorante',
            'sponsorizzato'     => '0',
            'link_immagine'     => 'd2egcvq7li5bpq.cloudfront.net/it/images/restaurants/226783.gif',
            'info' 	            => 'Schiacciate',
        ], [
            'nome' 		        => 'Pokescuse',
            'indirizzo' 	    => 'Via Cortevecchia, 5',
            'num_tavoli'	    => '3',
            'id_ristoratore' 	=> '17',
            'disp_massima' 	    => '10',
            'menu' 	            => '19',
            'pianta' 	        => '',
            'updated_at' 	    => date('Y-m-d h:i:s'),
            'created_at' 	    => date('Y-m-d h:i:s'),
            'tipo' 	            => 'Ristorante',
            'sponsorizzato'     => '1',
            'link_immagine'     => 'https://instagram.fblq3-1.fna.fbcdn.net/v/t51.2885-19/s150x150/57429774_420124115217506_8504389924479303680_n.jpg?_nc_ht=instagram.fblq3-1.fna.fbcdn.net&_nc_ohc=FFwk3tAX4EIAX96n4We&tp=1&oh=66ff4e6467bc02041d4a6e27373b543e&oe=60399E39',
            'info' 	            => 'Poke assemblabile',             
        ]]);
    }
}
